I have added navigation bar to visit different website sections
UniAuth/uniauth.github.io pull request #30
Opened 2021-03-18 13:04 UTC by Priyanshu078

Navigation bar with the links to visit different page sections

2021-03-18 18:42 UTC, YashKumarVerma requested changes
please add screenshot of the new site

2021-03-19 10:26 UTC, Priyanshu078 commented
Here are the screenshots
![uniauthscreeenshot](https://user-images.githubusercontent.com/66347715/111766529-a8671a80-88cb-11eb-8c65-41588936a96a.png)
![uniauthscreeenshot1](https://user-images.githubusercontent.com/66347715/111766585-b61ca000-88cb-11eb-81fc-046dea6e0bd0.png)

2021-03-22 14:11 UTC, YashKumarVerma approved these changes

2021-03-22 14:11 UTC, merged

2021-03-22 14:11 UTC, YashKumarVerma commented
thanks !